//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi24042019.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class haberler
    {
        public int haberID { get; set; }
        public string baslik { get; set; }
        public string link { get; set; }
        public string aciklama { get; set; }
    }
}
