//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi24042019.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MusteriDemographics
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MusteriDemographics()
        {
            this.Musteriler1 = new HashSet<Musteriler1>();
        }
    
        public string MusteriTypeID { get; set; }
        public string MusteriDesc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Musteriler1> Musteriler1 { get; set; }
    }
}
